# Generated by Django 6.0.3 on 2026-05-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.CharField()),
                ('completed_time', models.CharField()),
                ('deadline_time', models.CharField()),
                ('deleted_time', models.CharField()),
            ],
        ),
    ]
