# Generated by Django 6.0.3 on 2026-05-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_time',
            field=models.CharField(default=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_time',
            field=models.CharField(default=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='deleted_time',
            field=models.CharField(default=None),
        ),
    ]
