# Generated by Django 6.0.3 on 2026-05-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_completed_time_alter_task_deadline_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deleted_time',
        ),
    ]
