# Generated by Django 6.0.3 on 2026-05-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_completed_time_remove_task_deadline_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='add_time',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_time',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_time',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_time',
            field=models.CharField(null=True),
        ),
    ]
