# Generated by Django 6.0.3 on 2026-05-14 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_add_time_task_completed_time_task_deadline_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2026, 5, 14, 20, 55, 22, 881816)),
        ),
    ]
