# Generated by Django 6.0.3 on 2026-05-14 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2026, 5, 14, 21, 4, 54, 495946)),
        ),
    ]
