# Generated by Django 6.0.3 on 2026-05-14 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_email_alter_task_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2026, 5, 15, 0, 26, 51, 794327)),
        ),
    ]
