# Generated by Django 6.0.3 on 2026-05-14 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_add_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='delt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.CharField()),
                ('email', models.CharField()),
                ('add_time', models.CharField()),
                ('completed_time', models.CharField(null=True)),
                ('deadline_time', models.CharField(null=True)),
                ('deleted_time', models.CharField(default=datetime.datetime(2026, 5, 15, 0, 42, 50, 35551))),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2026, 5, 15, 0, 42, 50, 34535)),
        ),
    ]
