# Generated by Django 6.0.3 on 2026-05-14 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_delt_alter_task_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delt',
            name='deleted_time',
            field=models.CharField(default=datetime.datetime(2026, 5, 15, 0, 54, 22, 433694)),
        ),
        migrations.AlterField(
            model_name='task',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2026, 5, 15, 0, 54, 22, 432693)),
        ),
    ]
