# Generated by Django 6.0.5 on 2026-05-14 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_delt_deleted_time_alter_task_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delt',
            name='completed_time',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delt',
            name='deadline_time',
            field=models.CharField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delt',
            name='deleted_time',
            field=models.CharField(default=datetime.datetime(2026, 5, 15, 0, 59, 17, 300786)),
        ),
        migrations.AlterField(
            model_name='task',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2026, 5, 15, 0, 59, 17, 299259)),
        ),
    ]
