# Generated by Django 6.0.5 on 2026-05-14 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_delt_completed_time_alter_delt_deadline_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delt',
            name='add_time',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='delt',
            name='completed_time',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='delt',
            name='deadline_time',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='delt',
            name='deleted_time',
            field=models.CharField(default=datetime.datetime(2026, 5, 15, 1, 3, 0, 190006)),
        ),
        migrations.AlterField(
            model_name='task',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2026, 5, 15, 1, 3, 0, 189000)),
        ),
    ]
