# Generated by Django 6.0.3 on 2026-05-16 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_delt_add_time_alter_delt_completed_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='delt',
            name='deleted_time',
            field=models.CharField(default=datetime.datetime(2026, 5, 17, 0, 12, 13, 40131)),
        ),
        migrations.AlterField(
            model_name='task',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2026, 5, 17, 0, 12, 13, 39140)),
        ),
    ]
