# Generated by Django 6.0.3 on 2026-05-16 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_category_alter_delt_deleted_time_alter_task_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='email',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delt',
            name='deleted_time',
            field=models.CharField(default=datetime.datetime(2026, 5, 17, 0, 16, 30, 147615)),
        ),
        migrations.AlterField(
            model_name='task',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2026, 5, 17, 0, 16, 30, 146608)),
        ),
    ]
