# Generated by Django 6.0.3 on 2026-05-16 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_category_email_alter_delt_deleted_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default='default'),
        ),
        migrations.AlterField(
            model_name='delt',
            name='deleted_time',
            field=models.CharField(default=datetime.datetime(2026, 5, 17, 0, 56, 32, 916293)),
        ),
        migrations.AlterField(
            model_name='task',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2026, 5, 17, 0, 56, 32, 916293)),
        ),
    ]
