# Generated by Django 6.0.3 on 2026-05-16 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_category_category_alter_delt_deleted_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delt',
            name='category',
            field=models.CharField(default='default'),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='default'),
        ),
        migrations.AlterField(
            model_name='delt',
            name='deleted_time',
            field=models.CharField(default=datetime.datetime(2026, 5, 17, 0, 58, 53, 851354)),
        ),
        migrations.AlterField(
            model_name='task',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2026, 5, 17, 0, 58, 53, 850347)),
        ),
    ]
