# Generated by Django 6.0.3 on 2026-05-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_delt_category_task_category_alter_delt_deleted_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delt',
            name='deleted_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
