# Generated by Django 6.0.3 on 2026-05-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_delt_deleted_time_alter_task_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_time',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_time',
            field=models.DateTimeField(default=2),
            preserve_default=False,
        ),
    ]
